# Generated by Django 3.2 on 2021-05-27 18:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Pot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=datetime.datetime(2021, 5, 28, 0, 7, 32, 597496))),
            ],
            options={
                'ordering': ['order_date'],
            },
        ),
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot_name', models.CharField(max_length=40)),
                ('pot_slug', models.SlugField(unique=True)),
                ('marked_price', models.IntegerField()),
                ('pot_description', models.TextField()),
                ('pot_color', models.CharField(max_length=30)),
                ('pot_size', models.CharField(max_length=40)),
                ('selling_price', models.IntegerField(null=True)),
                ('pot_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('pot_rating', models.SmallIntegerField()),
            ],
            options={
                'ordering': ['pot_name'],
            },
        ),
        migrations.CreateModel(
            name='PotsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('review_image', models.ImageField(blank=True, null=True, upload_to='pots/images')),
                ('pot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pots', to='pots.pot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'pot'],
            },
        ),
        migrations.CreateModel(
            name='Potorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pots.order_pot')),
                ('pot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pots.pot')),
            ],
        ),
        migrations.AddField(
            model_name='pot',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pots', to='pots.potscategory'),
        ),
        migrations.AddField(
            model_name='order_pot',
            name='pot',
            field=models.ManyToManyField(related_name='orders', through='pots.Potorder', to='pots.Pot'),
        ),
        migrations.AddField(
            model_name='order_pot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='pots.review')),
            ],
            options={
                'ordering': ['review'],
            },
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislikes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='pots.review')),
            ],
        ),
    ]
