# Generated by Django 3.2 on 2021-05-28 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0002_alter_order_pot_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pot',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 19, 15, 29, 223128)),
        ),
    ]
