# Generated by Django 3.2 on 2021-05-28 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0003_alter_order_pot_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pot',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 19, 21, 52, 766022)),
        ),
        migrations.AlterField(
            model_name='pot',
            name='pot_size',
            field=models.CharField(max_length=70),
        ),
    ]
