# Generated by Django 3.2 on 2021-06-03 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0006_auto_20210604_0105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pot_properties',
            new_name='pots_property',
        ),
        migrations.AlterField(
            model_name='order_pot',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 1, 6, 59, 766054)),
        ),
    ]
