# Generated by Django 3.2 on 2021-06-03 19:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0008_alter_order_pot_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pot',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 1, 8, 20, 377008)),
        ),
        migrations.AlterField(
            model_name='pots_property',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='pots.potscategory'),
        ),
    ]
