# Generated by Django 3.2 on 2021-06-03 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0009_auto_20210604_0108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pots_property',
            new_name='properties',
        ),
        migrations.AlterField(
            model_name='order_pot',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 1, 9, 15, 954766)),
        ),
    ]
