# Generated by Django 3.2 on 2021-06-03 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0010_auto_20210604_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pot',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 1, 9, 41, 128267)),
        ),
    ]
