# Generated by Django 3.2 on 2021-06-05 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0018_alter_order_pot_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pot',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 5, 23, 1, 31, 761354)),
        ),
        migrations.AlterField(
            model_name='pot',
            name='slug',
            field=models.SlugField(),
        ),
    ]
