# Generated by Django 3.2 on 2021-06-06 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0020_auto_20210606_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='quantity',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order_pot',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 22, 58, 9, 779110)),
        ),
    ]
