# Generated by Django 3.2 on 2021-06-06 18:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pots', '0021_auto_20210606_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pot',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='order_pot',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 23, 51, 42, 269964)),
        ),
        migrations.CreateModel(
            name='Quantity_pot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=0)),
                ('pot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pot_quantity', to='pots.pot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
