# Generated by Django 3.2 on 2021-06-06 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0022_auto_20210606_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pot',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 0, 55, 26, 392444)),
        ),
        migrations.AlterField(
            model_name='quantity_pot',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
