# Generated by Django 3.2 on 2021-06-07 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0023_auto_20210607_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pot',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 0, 31, 46, 588398)),
        ),
    ]
