# Generated by Django 3.2 on 2021-06-08 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0024_alter_order_pot_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pot',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 13, 4, 36, 974396)),
        ),
        migrations.AlterField(
            model_name='pot',
            name='pot_name',
            field=models.CharField(max_length=60),
        ),
    ]
