# Generated by Django 3.2 on 2021-06-08 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0025_auto_20210608_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity_pot',
            name='total_price',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order_pot',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 8, 16, 14, 18, 475082)),
        ),
    ]
