# Generated by Django 3.2 on 2021-06-10 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0030_auto_20210611_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default=' ', max_length=40),
        ),
        migrations.AlterField(
            model_name='order_pot',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 11, 0, 49, 15, 162764)),
        ),
    ]
