# Generated by Django 3.2 on 2021-06-10 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0031_auto_20210611_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='Flat_No',
        ),
        migrations.AlterField(
            model_name='order_pot',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 11, 0, 53, 11, 280510)),
        ),
    ]
