# Generated by Django 3.2 on 2021-06-10 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0032_auto_20210611_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Area_Colony',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='Landmark',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order_pot',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 11, 1, 6, 15, 238580)),
        ),
    ]
