# Generated by Django 3.2 on 2021-06-12 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0033_auto_20210611_0106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pot',
            options={'ordering': ['-pot_name']},
        ),
        migrations.AddField(
            model_name='quantity_pot',
            name='redirect_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order_pot',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 23, 0, 2, 227773)),
        ),
    ]
