# Generated by Django 3.2 on 2021-06-12 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0034_auto_20210612_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_pot',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 12, 23, 10, 58, 255241)),
        ),
    ]
