# Generated by Django 3.2 on 2021-06-16 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots', '0036_alter_order_pot_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='flat_no',
            field=models.CharField(default='1-A', max_length=10),
        ),
        migrations.AlterField(
            model_name='order_pot',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 23, 54, 39, 957606)),
        ),
    ]
